### PR TITLE
Allow long names when reading header

### PR DESCRIPTION
**Pull request by iantra**
Reading headers currently fails if byte 2 is not 0 as an attempt to exclude files that aren't single-part scan line files. 
However, if my understanding of the spec (page 6 at https://www.openexr.com/documentation/openexrfilelayout.pdf) is correct, b2 can also be equal to 4, which only indicates long attribute and channel names rather than any differences in how the data is structured. We seem to be able to deal with varying name lengths already, so no exception should be raised in this case. You might want to do some testing first to confirm that this is the case, though.

This should enable minexr to read exr files exported by cycles, since this seems to be the main difference compared to eevee.

### CODE REVIEW

**Comment by cheind** [comment]
Hey, are you referring to bit10 on page 6? If so, your code seems to be fine. I don't expect any side effects from parsing longer names, since the 255 bytes is not hardcoded afaik. 

I find it strange, however, that cycles produces different openexr files from eevee. Don't they use the same base functionality, or does it just happen that your attribute names are longer?

Could you change ` 'Unused flags in version field are not zero.'` to something like `Unsupported ...`, because I believe they are not unused but unsupported by this minimal parser.

**Comment by iantra** [comment]
Yeah, that's the bit I was referring to. 

It could just be a weird implementation detail of my attribute names, but I find that unlikely since the exact same set up works fine with eevee but fails with cycles. The following script runs fine on the default cube scene:
``` python
import bpy
import minexr
path = "tmp.exr"
bpy.data.scenes[0].render.engine = "BLENDER_EEVEE"
bpy.data.scenes[0].render.filepath = path
bpy.data.scenes[0].render.image_settings.file_format="OPEN_EXR"
bpy.data.scenes[0].render.image_settings.compression=0
bpy.data.scenes[0].render.image_settings.exr_codec="NONE"
bpy.ops.render.render(write_still=True)
with open(path, "rb") as fp:
        exr = minexr.load(fp)
```
But changing the render engine to 'CYCLES' makes it fail, and raises an error at exactly that assertion.

The `Unused flags` name was taken straight from that same documentation page at the bottom of the table. I'm fairly sure it's an implementation detail of the OpenEXR version 2.0 spec and not just the parser, but I'm happy to change it if you'd prefer something else.

**Comment by cheind** [comment]
which version of blender are you using? 

maybe you could add a sample .exr file (small one) to https://github.com/cheind/py-minexr/tree/develop/etc and add an additional test to https://github.com/cheind/py-minexr/blob/develop/minexr/tests/test_reader.py?

If the flags are unused by OpenEXR, then I'm fine.

**Comment by iantra** [comment]
I'm running this in 2.92

After some more experimenting, it seems this error doesn't happen when rendering through the GUI, only if you render through the python module. Maybe it's something about the default render settings that somehow only applies to cycles?

I can add the sample files and extra tests tomorrow

**Comment by cheind** [comment]
hmm, interesting.

ok, thanks. will merge then

**Comment by iantra** [comment]
On further inspection, it seems to be an issue only with saving in the "OPEN_EXR" format from a script. Both "OPEN_EXR" 
 and "OPEN_EXR_MULTILAYER" work fine with both render engines when saved from a file output node, but the former seems to somehow cause this issue when rendered with Cycles from `bpy.ops.render.render`. I have the exact same settings for my output node and my scene output properties, and rendering from a command works fine with Eevee. Very strange.

**Comment by cheind** [comment]
Thanks for your work! Looking good.

**Pull request merged**
